[definition.vec]
headers = ["stdme/generic_sources/header/vec_C__PREFIX__.h__TEMPLATE__"]
sources = [
	"stdme/generic_sources/src/vec/C__PREFIX__.c__TEMPLATE__",
	"stdme/generic_sources/src/vec/C__PREFIX___sort.c__TEMPLATE__",
	"stdme/generic_sources/src/vec/C__PREFIX___functions2.c__TEMPLATE__",
	"stdme/generic_sources/src/vec/C__PREFIX___functions3.c__TEMPLATE__",
	"stdme/generic_sources/src/vec/C__PREFIX___functions4.c__TEMPLATE__",
]
replace.C__TYPENAME__ = "type"
replace.C__TYPEHEADER__ = "header_include"
replace.C__PREFIX__ = "prefix"
replace.C__PREFIXUP__ = "prefix"


[definition.hashmap]
headers = ["stdme/generic_sources/header/hashmap_C__PREFIX__.h__TEMPLATE__"]
sources = [
	"stdme/generic_sources/src/hashmap/C__PREFIX__.c__TEMPLATE__",
	"stdme/generic_sources/src/hashmap/C__PREFIX___utils.c__TEMPLATE__",
	"stdme/generic_sources/src/hashmap/C__PREFIX___iter.c__TEMPLATE__",
	"stdme/generic_sources/src/hashmap/C__PREFIX___clone.c__TEMPLATE__",
	"stdme/generic_sources/src/hashmap/C__PREFIX___clear.c__TEMPLATE__",
]
replace.C__VALTYPE__ = "type"
replace.C__KEYTYPE__ = "type"
replace.C__TYPEHEADER__ = "header_include"
replace.C__PREFIX__ = "prefix"
replace.C__PREFIXUP__ = "prefix"

[[create.vec]]
sources_output = "src/vec/C__PREFIX__/"
headers_output = "include/me/vec/"
replace.C__TYPENAME__ = "t_tile"
replace.C__TYPEHEADER__ = '#include "app/tile.h"'
replace.C__PREFIX__ = "tile"
replace.C__PREFIXUP__ = "TILE"

[[create.hashmap]]
sources_output = "src/hashmap/C__PREFIX__/"
headers_output = "include/me/hashmap/"
replace.C__VALTYPE__ = "t_string"
replace.C__KEYTYPE__ = "t_texture"
replace.C__PREFIX__ = "texture_path"
replace.C__PREFIXUP__ = "TEXTURE_PATH"
replace.C__TYPEHEADER__ = '''
#include "app/textures.h"
#include "me/string/string.h"
'''
